// Lists the debuff skills (effects aimed at other runners) with where they can trigger, from
// alpha123's Umalator skill data, and writes data/debuffs.js for the parent deck builder.
// Usage: node tools/build_debuffs.js <umalator-global dir> <umalator jp dir> <GameTora skills.json>
'use strict';
const fs = require('fs');
const path = require('path');
const [dirG, dirJ, gtFile] = process.argv.slice(2);
const load = (d, f) => { const p = path.join(d, f); return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : {}; };
const gt = new Map(JSON.parse(fs.readFileSync(gtFile, 'utf8')).map((s) => [String(s.id), s]));
// Effects that hurt whoever they hit: stamina, current/target speed, acceleration, vision,
// and type 13 (makes them rushed).
const HARM = new Set([8, 9, 13, 21, 22, 27, 31]);
const out = {};
for (const dir of [dirG, dirJ]) {
  const data = load(dir, 'skill_data.json');
  const meta = load(dir, 'skill_meta.json');
  const names = load(dir, 'skillnames.json');
  for (const [id, v] of Object.entries(data)) {
    if (out[id] || v.rarity >= 3) continue;
    const alt = v.alternatives[0];
    const hits = alt.effects.filter((e) => e.target && e.target !== 1 && HARM.has(e.type) && (e.modifier < 0 || e.type === 13));
    if (!hits.length) continue;
    const cond = v.alternatives.map((a) => a.precondition + '&' + a.condition).join('|');
    const pick = (re) => Array.from(new Set(Array.from(cond.matchAll(re)).map((m) => +m[1])));
    const g = gt.get(id);
    out[id] = {
      n: g ? (g.name_en || g.enname || g.jpname) : (names[id] ? names[id][names[id].length - 1] : '#' + id),
      r: v.rarity, // 1 white, 2 gold
      cost: (g && g.cost) || (meta[id] && meta[id].baseCost) || 0,
      gl: g && g.name_en ? 1 : 0,
      dist: pick(/distance_type==(\d)/g), // 1 sprint, 2 mile, 3 medium, 4 long; empty = any
      style: pick(/(?:^|[&|])running_style==(\d)/g), // the user's own style; 1 front ... 4 end
      ground: pick(/ground_type==(\d)/g), // 1 turf, 2 dirt
      power: Math.round(hits.reduce((a, e) => a + Math.abs(e.modifier) / (e.type === 13 ? 1000 : e.type === 8 ? 10000 : 100), 0)),
    };
  }
}
fs.writeFileSync('data/debuffs.js', "// Generated by tools/build_debuffs.js from alpha123's Umalator skill data. Do not edit.\n" +
  '(function (root) {\n  const DEBUFFS = ' + JSON.stringify(out) + ';\n' +
  '  if (typeof module !== "undefined" && module.exports) module.exports = DEBUFFS;\n  else root.UmaDebuffs = DEBUFFS;\n' +
  '})(typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : globalThis);\n');
console.log(Object.keys(out).length, 'debuffs');
